baseURL: http://example.org/
title: "Victor's Bench"
theme: "victors-bench-hugo-theme"

# Locales
defaultContentLanguage: "en"
defaultContentLanguageInSubDir: true
enableMissingTranslationPlaceholders: false
hasCJKLanguage: false
languageCode: "en"
removePathAccents: true
