# Render
canonifyURLs: false
uglyurls: false
disableAliases: false
disableHugoGeneratorInject: false
disableKinds: []
disableLiveReload: false
enableEmoji: true
enableGitInfo: false
ignoreCache: false
ignoreFiles: []
metaDataFormat: "yaml"
verbose: true
watch: true

# Build
cleanDestinationDir: true
buildDrafts: true
buildFuture: true
buildExpired: false

# Source Tree
# All site related content folders lives under 'src'
archetypeDir: "src/archetypes"
i18nDir: "src/locales"
contentDir: "src/content"
dataDir: "src/data"
layoutDir: "src/layouts"
staticDir: "src/static"

# Build Output
publishDir: "build"

# Themes
themesDir: "themes"
